-- Add crop state columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_crop_x DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_crop_y DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_zoom DOUBLE PRECISION DEFAULT 1.0;

ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_crop_x DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_crop_y DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_zoom DOUBLE PRECISION DEFAULT 1.0;
